project:
  type: website

website:
  title: "spotify-dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dashboard.qmd
      
format:
  html:
    theme: [cosmo, custom.scss]
    toc: true

editor: visual

